packages:
    - 'packages/*'

catalog:
    'vite': '5.4.15'
    'vitest': '3.0.5'
    '@vitest/ui': '3.0.9'
catalogs:
    svelte:
        'svelte': '5.19.7'
        '@sveltejs/kit': '2.20.2'
        'svelte-check': '4.1.4'
        '@sveltejs/vite-plugin-svelte': '5.0.3'
        '@sveltejs/adapter-static': '3.0.8'
    redux:
        '@reduxjs/toolkit': '^2.5.0'
